apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alert-rules
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: app.rules
      rules:
        - alert: PodDown
          expr: kube_pod_status_ready{condition="true"} == 0
          for: 30s
          labels:
            severity: critical
          annotations:
            summary: "Pod is down"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not ready"
