apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-client
  labels:
    app: blog-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-client
  template:
    metadata:
      labels:
        app: blog-client
    spec:
      containers:
        - name: blog-client
          image: harivp1234/blog-client:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
