apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-server
  labels:
    app: blog-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-server
  template:
    metadata:
      labels:
        app: blog-server
    spec:
      containers:
        - name: blog-server
          image: harivp1234/blog-server:latest
          imagePullPolicy: Never   # important when using local images with kind
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/BlogApp
